  name: Backport

  on:
    pull_request:
      types: labeled
      branches:
      - master

  jobs:
    backport:
      runs-on: ubuntu-latest
      steps:
      - uses: hmharvey/act-on-label@master
        with:
          labels: 'backport'
      - uses: actions/checkout@v1.1.0
        with:
          ref: 'stable-branch'
      - uses: hmharvey/cherry-pick-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "output env ${{ env.OUTPUT_BRANCH_NAME }} or ${{ outputs.branch_name }}"
      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: 'stable-branch'
