  name: Octokit v4 Backport

  on:
    pull_request:
      types: labeled
      branches:
      - master

  jobs:
    backport:
      runs-on: ubuntu-latest
      steps:
      - uses: hmharvey/act-on-label@master
        with:
          labels: 'backport'
      - uses: unsplash/comment-on-pr@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           msg: "It worked!"
